{
    "name": "Sale Order Line History & Audit Log",
    "version": "19.0.1.1.0",
    "summary": "Full audit trail for sale order lines — track every add, edit, and removal directly in the chatter.",
    "author": "Mouad Lyaazale",
    "maintainer": "Mouad Lyaazale",
    "support": "mouad.lyaazale@gmail.com",
    "website": "mailto:mouad.lyaazale@gmail.com",
    "license": "OPL-1",
    "category": "Sales/Sales",
    "price": 29.00,
    "currency": "USD",
    "depends": ["sale_management", "mail"],
    "data": [],
    "images": ["static/description/banner.png"],
    "installable": True,
    "application": False,
    "auto_install": False,
}
